apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-exporter
  name: redis-exporter
spec:
  ports:
  - name: "2112"
    port: 2112
    targetPort: 2112
  selector:
    app: redis-exporter
status:
  loadBalancer: {}
